### ISSUE TITLE
promiseDownloadTaskWithURL does fulfill with a deleted file

### ISSUE THREAD

**Issue by jschmid** [jschmid/NSURLSession-PromiseKit#1]
When the promise returned by `promiseDownloadTaskWithURL` calls his `then`, the temporary file created by NSURLSession has already been deleted. We cannot take the file from the `then` and move it to a non-temporary folder.

**Comment by Kirow** [comment]
Same issue with `promiseDataTaskWithRequest`. I've made code change for myself, don't see another way.

``` Objective-C
[PMKPromise new:^(PMKFulfiller fulfill, PMKRejecter reject) {
    NSURLSessionDownloadTask *task = [[NSURLSession sharedSession] downloadTaskWithURL:[NSURL URLWithString:url] completionHandler: ^(NSURL *location, NSURLResponse *response, NSError *error) {
        if (error) {
            reject(error);
        } else {
            NSError *fmError = nil;
            NSString *path = ...
            if (![manager moveItemAtPath:location.path toPath:path error:&fmError]) {
                reject(error);
            } else {
                fulfill(path);
            }
        }
    }];
    [task resume];
}]
```

But in this case I need to delete file manually.

I think best way is to add destination path to method signature.

**Comment by jschmid** [comment]
That is indeed what I resorted to do. I try to get a fix quickly.

**Comment by jschmid** [comment]
@Kirow  I pushed v0.3.0

**Comment by Kirow** [comment]
@jschmid ok, thx :thumbsup:
