### ISSUE TITLE
Update to use PromiseKit 2

### ISSUE THREAD

**Issue by ccheever** [jschmid/NSURLSession-PromiseKit#8]
If you're using the latest version of PromiseKit (2.1), you can't use NSURLSession-PromiseKit because NSURLSession-PromiseKit specifies that it requires ~>1.0
- `PromiseKit/Promise (~> 1.0)` required by `NSURLSession-PromiseKit (0.3.0)`

It would be good to have a version of this that supports the latest version of PromiseKit!

**Comment by jschmid** [comment]
Sorry I am deprecating the lib 32ef40795bfe4c18248603bcb0c95e16d5afb437

**Comment by sstadelman** [comment]
@jschmid Hi, I especially like your implementation, particularly how it is so close to the original `NSURLSession` API set.  I expressed this to @mxcl here:  https://github.com/mxcl/PromiseKit/issues/403, but I wanted to check to see if there is history for why this was not carried forward or into the main project.  Anything to be aware of if updating to PromiseKit 3?
--Stan
